# Generated by Django 4.2.11 on 2024-05-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_comment_approved_comment_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='has_sponsor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='sponsor',
            field=models.CharField(default='Embratel'),
        ),
    ]
