# Generated by Django 4.2.11 on 2024-05-29 18:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_post_has_sponsor_post_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='dfy0one9z', max_length=255, verbose_name='image'),
        ),
    ]
