# Generated by Django 4.2.11 on 2024-05-30 15:38

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Publication date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='dfy0one9z', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sponsor',
            field=models.CharField(default='Embratel', max_length=100),
        ),
    ]
